# name: observability

services:
  grafana-lgtm:
    container_name: grafana-lgtm
    image: grafana/otel-lgtm:latest
    restart: unless-stopped
    deploy:
      mode: replicated
      replicas: 1
      placement: 
        constraints: 
          - node.role == manager
      resources:
        limits:
          cpus: "0.1"
          memory: '50M'
      restart_policy:
        condition: any
    volumes:
      - prometheus_data:/data/prometheus
      - loki_data:/loki
      - tempo_data:/tmp/tempo
      - grafana_data:/otel-lgtm/grafana/data
    environment:
      - ENABLE_LOGS_ALL=true
    networks:
      traefik-net:
      observability:
        aliases:
          - lgtm
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana-lgtm.rule=Host(`grafana.dev-playground.net`)"
      - "traefik.http.routers.grafana-lgtm.middlewares=default-middlewares@file"
      - "traefik.http.services.grafana-lgtm.loadbalancer.server.port=3000"
      - "traefik.docker.network=traefik-net"

  netdata:
    image: netdata/netdata
    container_name: netdata
    pid: host
    restart: unless-stopped
    deploy:
      mode: replicated
      replicas: 1
      placement: 
        constraints: 
          - node.role == manager
      resources:
        limits:
          cpus: "0.1"
          memory: '50M'
      restart_policy:
        condition: any
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    volumes:
      - netdataconfig:/etc/netdata
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata
      - /:/host/root:ro,rslave
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /etc/localtime:/etc/localtime:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
      - /var/log:/host/var/log:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      traefik-net:
      observability:
        aliases:
          - netdata
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.netdata-auth.basicauth.users=gabra:$$apr1$$8BYoCqr8$$Tdd4HO1OwcygvfYSNawy4/"
      - "traefik.http.routers.netdata.rule=Host(`netdata.dev-playground.net`)"
      - "traefik.http.routers.netdata.middlewares=netdata-auth, default-middlewares@file"
      - "traefik.http.services.netdata.loadbalancer.server.port=19999"
      - "traefik.docker.network=traefik-net"

networks:
  traefik-net:
    external: true
  observability:
    external: true

volumes:
  netdataconfig:
  netdatalib:
  netdatacache:
  grafana_data:
  prometheus_data:
  loki_data:
  tempo_data: