# name: setup

services:
  traefik:
    container_name: traefik
    image: traefik:v3.1
    restart: unless-stopped
    deploy:
      mode: replicated
      replicas: 1
      placement: 
        constraints: 
          - node.role == manager
      restart_policy:
        condition: any
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
      - ./traefik.yml:/traefik.yml
      - ./dynamic.yml:/dynamic.yml
    env_file: "dns.env"
    command:
      - "--configFile=/traefik.yml"
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=gabra:$$apr1$$8BYoCqr8$$Tdd4HO1OwcygvfYSNawy4/"
      - "traefik.http.routers.traefik.rule=Host(`traefik.dev-playground.net`)"
      - "traefik.http.routers.traefik.middlewares=traefik-auth, default-middlewares@file"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.docker.network=traefik-net"
    networks:
      - traefik-net
      - observability
    depends_on:
      - error-pages

  sablier:
    container_name: sablier
    image: acouvreur/sablier:1.7.0
    restart: unless-stopped
    deploy:
      mode: replicated
      replicas: 1
      placement: 
        constraints: 
          - node.role == manager
      restart_policy:
        condition: any
    command:
      - "start"
      - "--provider.name=swarm"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  error-pages:
    container_name: error-pages
    image: ghcr.io/tarampampam/error-pages:3
    restart: unless-stopped
    deploy:
      mode: replicated
      replicas: 1
      placement: 
        constraints: 
          - node.role == manager
      restart_policy:
        condition: any
    environment:
      TEMPLATE_NAME: hacker-terminal
    command:
      - "serve"
    labels:
      - "traefik.enable=true"
      - "sablier.enable=true"
      - "sablier.group=server"
      - "traefik.http.routers.error-pages.rule=Host(`errors.dev-playground.net`)"
      - "traefik.http.routers.error-pages.priority=10"
      - "traefik.http.routers.error-pages.middlewares=default-middlewares@file"
      - "traefik.http.services.error-pages.loadbalancer.server.port=8080"
      - "traefik.docker.network=traefik-net"
    networks:
      - traefik-net

networks:
  traefik-net:
    external: true
  observability:
    external: true