# name: pipelines

services:
  registry:
    image: registry:2
    deploy:
      mode: replicated
      replicas: 1
      placement: 
        constraints: 
          - node.role == manager
      restart_policy:
        condition: any
    ports:
      - 127.0.0.1:5000:5000
    volumes:
      - registry_data:/var/lib/registry
    networks:
      pipelines:
        aliases:
          - registry

  jenkins:
    image: jenkinswithdockercli:latest
    deploy:
      mode: replicated
      replicas: 1
      placement: 
        constraints: 
          - node.role == manager
      restart_policy:
        condition: any
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      pipelines:
        aliases:
          - jenkins
      ingress-net:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jenkins.rule=Host(`jenkins.dev-playground.net`)"
      - "traefik.http.routers.jenkins.middlewares=default-middlewares@file"
      - "traefik.http.services.jenkins.loadbalancer.server.port=8080"
      - "traefik.docker.network=ingress-net"


  portainer:
    image: portainer/portainer-ce:latest
    deploy:
      mode: replicated
      replicas: 1
      placement: 
        constraints: 
          - node.role == manager
      restart_policy:
        condition: any
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      ingress-net:
      pipelines:
        aliases:
          - portainer

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer.dev-playground.net`)"
      - "traefik.http.routers.portainer.middlewares=default-middlewares@file"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
      - "traefik.docker.network=ingress-net"

  sonarqube-db:
    image: postgres:16-alpine
    deploy:
      mode: replicated
      replicas: 1
      placement: 
        constraints: 
          - node.role == manager
      restart_policy:
        condition: any
    volumes:
      - sonarqube_db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    networks:
      pipelines:
        aliases:
          - sonarqube-db

  sonarqube:
    image: sonarqube:community
    deploy:
      mode: replicated
      replicas: 1
      placement: 
        constraints: 
          - node.role == manager
      restart_policy:
        condition: any
    volumes:
      - sonarqube_data:/opt/sonarqube/
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonarqube-db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    networks:
      ingress-net:
      pipelines:
        aliases:
          - sonarqube
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarqube.rule=Host(`sonarqube.dev-playground.net`)"
      - "traefik.http.routers.sonarqube.middlewares=default-middlewares@file"
      - "traefik.http.services.sonarqube.loadbalancer.server.port=9000"
      - "traefik.docker.network=ingress-net"
    depends_on:
      - sonarqube-db

networks:
  pipelines:
    external: true
  ingress-net:
    external: true

volumes:
  registry_data:
    external: true
  jenkins_home:
    external: true
  portainer_data:
    external: true
  sonarqube_data:
    external: true
  sonarqube_db:
    external: true