# name: ingress

services:
  traefik:
    container_name: traefik
    image: traefik:v3.1
    deploy:
      mode: replicated
      replicas: 1
      placement: 
        constraints: 
          - node.role == manager
      restart_policy:
        condition: any
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
      - ./traefik.yml:/traefik.yml
      - ./dynamic.yml:/dynamic.yml
    env_file: "dns.env"
    command:
      - "--configFile=/traefik.yml"
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=gabra:$$apr1$$8BYoCqr8$$Tdd4HO1OwcygvfYSNawy4/"
      - "traefik.http.routers.traefik.rule=Host(`traefik.dev-playground.net`)"
      - "traefik.http.routers.traefik.middlewares=traefik-auth, default-middlewares@file"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.docker.network=ingress"
    networks:
      - ingress
      - observability
    depends_on:
      - error-pages

  error-pages:
    container_name: error-pages
    image: ghcr.io/tarampampam/error-pages:3
    deploy:
      mode: replicated
      replicas: 1
      placement: 
        constraints: 
          - node.role == manager
      restart_policy:
        condition: any
    environment:
      TEMPLATE_NAME: hacker-terminal
    command:
      - "serve"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.error-pages.rule=Host(`errors.dev-playground.net`)"
      - "traefik.http.routers.error-pages.middlewares=default-middlewares@file"
      - "traefik.http.services.error-pages.loadbalancer.server.port=8080"
      - "traefik.docker.network=ingress"
    networks:
      - ingress

networks:
  ingress:
    external: true
  observability:
    external: true