name: setup

services:
  traefik:
    container_name: traefik
    image: traefik:v3.1
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
      - ./traefik.yml:/traefik.yml
    env_file: "dns.env"
    command:
      - "--configFile=/traefik.yml"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.dev-playground.net`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=gabra:$$apr1$$8BYoCqr8$$Tdd4HO1OwcygvfYSNawy4/"
      - "traefik.http.routers.traefik.middlewares=traefik-auth"
      - "traefik.docker.network=traefik-net"
    networks:
      - traefik-net
    depends_on:
      - error-pages

  error-pages:
    container_name: error-pages
    image: ghcr.io/tarampampam/error-pages:3
    restart: unless-stopped
    environment:
      TEMPLATE_NAME: hacker-terminal
    command:
      - "serve"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.error-pages.rule=Host(`errors.dev-playground.net`)"
      - "traefik.http.routers.error-pages.priority=10"
      - "traefik.http.services.error-pages.loadbalancer.server.port=8080"
      - "traefik.docker.network=traefik-net"

    networks:
      - traefik-net

networks:
  traefik-net:
    external: true