entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: myresolver
        domains:
          - main: dev-playground.net
            sans:
              - "*.dev-playground.net"
    asDefault: true

providers:
  docker:
    exposedByDefault: false
  swarm: true

ping: true
accessLog: true
api:
  dashboard: true

http:
  middlewares:
    error-pages-middleware:
      errors:
        status:
          - "400-599"
        service: error-pages
        query: "/{status}.html"

certificatesResolvers:
  myresolver:
    acme:
      email: george.ayad@icloud.com
      storage: /letsencrypt/acme.json
      dnsChallenge:
        provider: linode

tracing:
  addInternals: true
  otlp:
    grpc:
      endpoint: otel-collector:4317
      insecure: true
  sampleRate: 0.2
  serviceName: traefik